### ISSUE TITLE
Get silenced when chatting while bancho/internet lagging

### ISSUE THREAD

**Issue by mirusu400** [ppy/osu-stable-issues#10]
While bancho not working or internet not working for a seconds, we chat something slowly, but after bancho re-connected / internet re-connected Banchobot recognized that we are spam chatting and we usually got silenced by him.

It happens because osu! client promptly send legacy chattings when bancho reconnected.
So It should be changed not to send chattings and alert users(Like discord)

**Comment by peppy** [comment]
Unfortunately due to the way bancho communication works (it's very much a stream connection rather than a REST api) this is a hard one to fix. I would also argue it's a pretty rare case, and can be resolved by reaching out to support if you encounter it.

This is a known issue and already fixed in lazer.
