### ISSUE TITLE
If the first object / offset of a beatmap is between 0ms and 30ish ms starting the map causes a lagspike

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-stable-issues#1090]
Reported in  **\#nat** : 

Secre: 
do other modes have the problem of when a map starts at betwen 00:00:00-00:00:30~ is there a lag spike at the start
example of that is https://osu.ppy.sh/beatmapsets/474675#osu/1013839

Hivie: 
for taiko yes 

Protastic101:
Mania also yes

Dada: 
I have encountered that for osu! in the past

**Currently the solution is giving people mp3s with different offsets, I'd rather avoid putting a thing that seems like "ah yes this is how you manually circumvent a bug" into the RC**

**Comment by peppy** [comment]
Tracked at https://github.com/ppy/osu/issues/22488.

I don't think this will be fixed in stable, but will in the future. I also don't think it should be in the ranking guidelines, but it it's causing an issue with playability of a specific beatmap then please apply a fix locally to that beatmap only.

**Comment by miyuki-ts** [comment]
> Tracked at [ppy/osu#22488](https://github.com/ppy/osu/issues/22488).
> 
> I don't think this will be fixed in stable, but will in the future. I also don't think it should be in the ranking guidelines, but it it's causing an issue with playability of a specific beatmap then please apply a fix locally to that beatmap only.

how do i fix it locally to that beatmap.
