### ISSUE TITLE
My cursor stops moving sometimes while playing

### ISSUE THREAD

**Issue by maor727** [ppy/osu-stable-issues#1142]
Its happening like every 2 day or something like that. I can't move my mouse or neither my tablet and I have to restart the game in order to continue playing. 
![image](https://github.com/ppy/osu-stable-issues/assets/68875758/73de0ff7-45eb-4005-84da-897e36e5d754)
nothing on the event viewer and when its happening my instant replay doesn't work because it doesnt detect the game.

**Comment by smoogipoo** [comment]
Have you tried unplugging/replugging your mouse/tablet? This shouldn't be related to osu! itself since you're the only one that's experienced this, so if it's not that then it's likely some other program on your PC perhaps opening an overlay that's stealing input - try closing background programs (ShareX, Discord, Overwolf, OBS, etc) assuming Alt+Tab doesn't fix it for you.
