### ISSUE TITLE
Mouse buttons get disabled although the option isn't turned on

### ISSUE THREAD

**Issue by Rrebmoz** [ppy/osu-stable-issues#1250]
First some background: I use my keyboard and mouse to click, I click with my mouse for aim/jumps and I press on my keyboard for streams.

When I accidentally hold down a mouse button I can still press the buttons on my keyboard, but when I accidentally hold down a button on my keyboard the mouse buttons get disabled although option "Disable mouse buttons in play mode" is not enabled.

**Comment by smoogipoo** [comment]
If it's a matter of, for example, holding down K1 and trying to press M2, and that's not working, then it's an issue with some other software on your PC.

Otherwise, the game is correctly handling the exclusivity between K1/M1 and K2/M2, and the in-game input overlay is displaying it somewhat incorrectly.
