### ISSUE TITLE
Beatmap Pack #267 has a Graveyard map; instead another Ranked map isn't counted in Beatmap Packs at all

### ISSUE THREAD

**Issue by MasterAnimit** [ppy/osu-stable-issues#1254]
In 2012, [during BP #267 creation](https://osu.ppy.sh/beatmaps/packs/S267) [an Unranked map was added](https://osu.ppy.sh/beatmapsets/59586#osu/178527), never updated from a day of its upload to game.

It's probably a mistake, because [another Ranked map](https://osu.ppy.sh/beatmapsets/59286#osu/183361) doesn't appear in ANY BP on page and in-game. Its mapset ID is 59**2**86, so DeathxShinigami probably failed and put ID 59**5**86 there by accident.

![image](https://github.com/user-attachments/assets/1c0f4590-dcb4-43c6-b216-72d25cf08cbd)
![image](https://github.com/user-attachments/assets/240f6155-8cc2-43cc-a200-0ed959e150a4)

**Comment by MasterAnimit** [comment]
I wasn't sure there to put it so it landed on Stable bug branch, I saw other Beatmap Pack related things landed here in past

**Comment by Sitoria** [comment]
sorry for late, i will handle this one

**Comment by Sitoria** [comment]
Due to [Hanz Up!](https://osu.ppy.sh/beatmapsets/43510) Mapset is DMCA'd by NEOWIZ, new pack will no more having this mapset's mp3. 
re-packed, if you find any other issue like this on beatmap pack section, please DM to `Shige-Tori[a]` next time.
![image](https://github.com/user-attachments/assets/2a788ad9-f7d7-4c7f-a99d-2e9df2e5621f)
@peppy it is fixed now, can be closed.

**Comment by MasterAnimit** [comment]
> if you find any other issue like this on beatmap pack section, please DM to `Shige-Tori[a]` next time.

Thanks! Appreciated.
