### ISSUE TITLE
The beginning of the map runs very very quickly

### ISSUE THREAD

**Issue by valnesfjord** [ppy/osu-stable-issues#1256]
# Bug description
I start any map, at random intervals and several times at the start of a map it plays very quickly and I literally don't have time to hit the notes and immediately loose it. This bug is observed for 1.5 years on different versions of the game on my own hardware (for example, on a laptop everything is normal)
Sometimes it happens a couple of times per game, and sometimes on one map all the time

# PC specs
PC:
i5 12400f
rtx 3080
32 gb ddr5 6133 cl 30 tuned
Official Windows 11
240hz monitor

Game on PCIe4 SSD
Game version: latest 20241001

# Screenshots or videos

https://github.com/user-attachments/assets/48d04a88-32f6-4bc9-9663-ed8840ea704f

# Logs

[runtime.log](https://github.com/user-attachments/files/17401914/runtime.log)
[session.log](https://github.com/user-attachments/files/17401915/session.log)

**Comment by smoogipoo** [comment]
This is caused by the audio driver, which sounds like it's running in some sort of catchup mode.

This is not something that we can resolve, and I don't have any solutions for you other than:
- Disable/remove any audio latency reducing software like REAL.
- Check for any audio driver updates.
- Use a different audio output.
