### ISSUE TITLE
Trying to send a message to a user with a space in their name via ingame irc will send a duplicate message to a user with a similar name

### ISSUE THREAD

**Issue by Dawnsday** [ppy/osu-stable-issues#289]
Title was written at 4am GMT so allow me to elaborate

If using ingame IRC, any messages sent to a username containing spaces (IE: "This Name Is Fake") will be duplicated and sent to anyone who has that name with the space replaced by underscores (IE: "This_Name_Is_Fake"). As far as I'm aware this is a new-ish issue, but due to the peculiar happenstance of the bug I can't test that hypothesis.

Forgive the lack of QA formatting/explanations.

**Comment by omkelderman** [comment]
from what I know two users with usernames like that should be considered duplicates and it shouldnt happen that they both exist at the same time. Since when connecting to bancho with the IRC protocol all spaces will be replaced with underscores since a space is an illegal character for a username in the IRC spec.

However, I actually have seen this problem in action before where someone had problems using Tillerino. That user was https://osu.ppy.sh/users/2958963 (username "John Cena"), but tillerino was sending responses back to https://osu.ppy.sh/users/7951921 (username "John_Cena"). This happened in October 2018, but I never reported it cuz idk actually why.. Either way, both users appear to still exist with those usernames. From memory the message was actually not duplicated but just send to the user with the underscore in the name. But that difference might be because of irc connection vs ingame chat.

**Comment by peppy** [comment]
i've checked the code and "duplicate" messages can not be sent. at the same time, we don't allow such usernames to exist, so it should not be an issue that they clash in the first place. if such usernames exist (it used to be allowed many years ago), we can offer a free username change.
