### ISSUE TITLE
Incorrect offset on beatmap post bass changes

### ISSUE THREAD

**Issue by peppy** [ppy/osu-stable-issues#326]
Tracking [this tweet](https://twitter.com/rtaMxi/status/1216516571952074753).

Can reproduce on stable and lazer, requires further investigation.

Correct offset looks to be around 298, not 372.

**Comment by peppy** [comment]
Re-encoding the mp3 looks to fix the issue. Could others please test using this mp3 instead: https://puu.sh/EZEOO/fe0685db40.mp3

**Comment by peppy** [comment]
Please provide any examples of other beatmaps with a similar issue (mistimed more than 50ms on stable, but only in the last week – since the audio library update).

**Comment by McKay42** [comment]
This is https://github.com/ppy/osu-stable-issues/issues/312 , no?

**Comment by peppy** [comment]
@McKay42 i'm not 100% sure, so I wanted to track this separately. The offset inaccuracy reported here is much larger, and only occurs on very specific MP3s. It is also consistent across all PCs, including my own.

**Comment by peppy** [comment]
```
➜  ~  eyeD3 -P lameinfo ~/Projects/Neurotoxin-broken.mp3                                                   [ 3.57 MB ]
-------------------------------------------------------------------------------------------------------------------
Encoder Version     : LAMEUUUUU
LAME Tag Revision   : 10
VBR Method          : Variable Bitrate method3 (mt)
Lowpass Filter      : 8500
Peak Amplitude      : 170.66666663 (+44.6 dB)
Audiofile Replay Gain: 28.1 dB (Unknown)
Audiofile Replay Gain: 28.1 dB (Unknown)
Encoding Flags      : --nspsytune --nogap
No Gap              : after
ATH Type            : 5
Bitrate (Minimum)   : 85
Encoder Delay       : 1365 samples
Encoder Padding     : 1365 samples
Noise Shaping       : 1
Stereo Mode         : Auto
Unwise Settings     : False
Sample Frequency    : 44.1 kHz
MP3 Gain            : 85 (+127.5 dB)
Preset              : 1365
Surround Info       : DPL2 encoding
Music Length        : 1.33 GB
Music CRC-16        : 5555
LAME Tag CRC-16     : BA36
```

```
➜  ~  eyeD3 -P lameinfo ~/Projects/Neurotoxin-good.mp3 
/Users/dean/Projects/Neurotoxin-good.mp3                                                               [ 4.77 MB ]
-------------------------------------------------------------------------------------------------------------------
Encoder Version     : LAME3.100
LAME Tag Revision   : 0
VBR Method          : Constant Bitrate
Lowpass Filter      : 19700
Encoding Flags      : --nspsytune --nssafejoint
ATH Type            : 4
Bitrate (Constant)  : 256
Encoder Delay       : 576 samples
Encoder Padding     : 576 samples
Noise Shaping       : 1
Stereo Mode         : Joint
Unwise Settings     : False
Sample Frequency    : 44.1 kHz
MP3 Gain            : 0 (+0.0 dB)
Preset              : CBR 256
Surround Info       : None
Music Length        : 4.76 MB
Music CRC-16        : 349C
LAME Tag CRC-16     : AB17
```

- [x] Rule out VBR being the issue
- [ ] Rule out encoder delay/padding being the issue
- [ ] Rule out surround info being the issue
- [ ] Look into Preset
- [ ] Look into ATH type
- [ ] Look into encoder version

**Comment by Kyuunex** [comment]
Being a mapper and spending time in the editor, one thing I noticed is that the offset stored in .osu files don't actually correspond to the same point in the mp3 if I open it in audacity. It's like in osu, 50ms is truncates off the mp3 in the beginning. And I have had a case where the sound starts at a negative offset in the editor. Maybe updated bass lib handles this differently, I am not sure what goes behind the scenes but it's worth pointing out.

**Comment by peppy** [comment]
@Kyuunex this has always been the way, yep. Hopefully we can draw this closer in lazer.

**Comment by Peter-GHub** [comment]
Hey i've checked map and your mp3 I don't know if you are aware of this or not but exporting mp3 using some programs like audacity etc. adds delay to mp3 or maybe it's just showing it to me like that.

Here's screenshot of mp3 directly from map folder (Top) and your audio(Bottom) https://gyazo.com/86f2f7ef20eb29d6d36641499d8b9299 can you confirm if this is also the same for you? 

I actually subtracted 50ms to 322 from map offset to see if it's the case but i was surprised 50ms still sounded off by ~20 ms but exporting mp3 with audacity that adds 50 ms delay seemed to fix this problem at least that's what i thought after exporting mp3 it seems like perfect offset will be 392 not 372 then i used mp3 you linked above which sounds aligned perfectly it seems like your program adds ~30ms not 50ms

Screenshot of 3 audios https://gyazo.com/ff536df472d6c8da90a860b2a50c933b as you can see all of 3 of them use different offsets the one from audacity which exported map mp3 is most delayed while map mp3 is least delayed your mp3 is between them

it's still weird because your program added about 30ms not whole 64ms i have no idea where 34ms got added to it

It's also the case on audio compatibility mode I used fallback to compare offsets as well

**Comment by peppy** [comment]
It's very hard to understand what you're trying to say. Could you keep things simple and answer yes or no as to whether the mp3 i provided fixed the issue with no other changes?

**Comment by Peter-GHub** [comment]
To keep it short yep it did fix the offset, but the audio you provided got delayed by 30ms which is still weird because current mp3 seems to be late by 64ms in editor

**Comment by peppy** [comment]
The original had gapless information, which may be why your audio viewer shows "less delay".

**Comment by Peter-GHub** [comment]
Alright so I re-downloaded map again and I did something else instead and i think i found cause of problem removing Audio metadata seems to fix this issue as well https://gyazo.com/7a42ba8623498aa59b0bfcbd4599fa30 

can you try it yourself?

I think metadata of mp3 seems to be causing problems

**Comment by Kyuunex** [comment]
pog

i just tried removing id3 tags from the mp3 from the audio in question and it fixed it.
the mp3 file has 2 id3 tags, ID3v1.1 tag and ID3v2.3.0 tag. removing just ID3v2.3.0 fixed it. removing just ID3v1.1did not.

**Comment by Karoo13** [comment]
I _think_ audacity timing errors are due to it showing skipped samples at the start of the mp3, while bass skips the samples as intended. Usually 1152 samples are skipped (26.1ms), and average 5ms precision, this adds to 31.1ms difference between osu and audacity timing. Maybe also consider the hit being delayed by half the frametime on average.

I tested this in august, and it gave me good timing, though it may just be a coincidence that this number aligns with the observed difference. I also observed  that the new bass is giving me 5ms earlier hitsounds compared to fallback, but equal roundtrip latency (tested by mic recording keyboard and hitsound).

**Comment by peppy** [comment]
We've pinpionted the issue down to the appearance of `iTunSMPB`, which is an apple-specific gapless playback attribute. Will push a cutting edge build today which should resolve this issue, so please look out for it and test any beatmaps that seemed incorrect previously.

**Comment by peppy** [comment]
Is now live on cutting edge. Please test this beatmap and any others that may have been having issues.

**Comment by Peter-GHub** [comment]
Hey i've tested new update and it seems like map https://osu.ppy.sh/b/2237868 started to have problems with offset the timing sounds okay on stable and fallback

**Comment by peppy** [comment]
Could you provide more details? What is the offset required to fix the baetmap?

**Comment by peppy** [comment]
Can reproduce, thanks.

**Comment by McKay42** [comment]
> Is now live on cutting edge. Please test this beatmap and any others that may have been having issues.

On cuttingedge I now need -50 ms universal offset: https://www.youtube.com/watch?v=jmAQ0BFn_Es
while on stable I need +50 ms universal offset.

**Comment by peppy** [comment]
@McKay42 there was a slight issue which meant the offset could be applied multiple times. please test again with the next CE release.

**Comment by peppy** [comment]
@McKay42 please test again on 20200115.1

**Comment by McKay42** [comment]
> @McKay42 please test again on 20200115.1

Now needs +100 ms universal offset on 20200115.1

**Comment by peppy** [comment]
sorry i am incompetent. please try .2 in 5 minutes.

**Comment by McKay42** [comment]
> please try .2 in 5 minutes.

Neurotoxin is now almost perfect.

But, [Counting Stars](https://osu.ppy.sh/beatmapsets/1068991#osu/2237868) mentioned by @Peter-GHub still needs -50 ms universal offset (its mp3 also contains the `iTunSMPB` tag).

**Comment by peppy** [comment]
Yep, going to need to investigate further. My initial thoughts are that it has something to do with 

```
UserTextFrame: [Description: gapless_playback]
0
```

in `Counting Stars`, but I'm waiting to hear from the bass dev as to whether that is considered by bass.

**Comment by McKay42** [comment]
Would be cool to get a list of all non-backend changes in BASS which affect `BASS_ChannelGetPosition`, between 2009 and 2019. (i.e. changes which are unrelated to DirectSound or WASAPI, but still affect position)

**Comment by peppy** [comment]
Agree. `ItunSMPB`, for instance, was not mentioned in the changelog anywhere. Will convey this.

**Comment by peppy** [comment]
Please test latest CE build, which should now have fixed both of the mentioned beat maps in this thread.

**Comment by McKay42** [comment]
[Counting Stars](https://osu.ppy.sh/beatmapsets/1068991#osu/2237868) still needs a -50 ms universal offset on b20200116cuttingedge

**Comment by peppy** [comment]
Good catch. Can see why this is happening.

@McKay42 out of curiosity, which version of bass are you targeting for your own projects?

**Comment by peppy** [comment]
A new build has been pushed to fix Counting Stars.

**Comment by Peter-GHub** [comment]
Alright tested this one seems like timing got fixed for counting stars and then again got broken on https://osu.ppy.sh/beatmapsets/192995 
Tested on 20200116.2

Let me know if that's the case for you

**Comment by Wieku** [comment]
Yeah, Neurotoxin seems to be broken again, but Counting Stars is synced: https://streamable.com/t57st
It would be nice to know all the fixes needed to `BASS_ChannelGetPosition` start returning proper values again (besides `ItunSMPB` tag)

**Comment by McKay42** [comment]
> Yeah, Neurotoxin seems to be broken again, but Counting Stars is synced: https://streamable.com/t57st
> I would be thankful to know all the fixes needed to `BASS_ChannelGetPosition` start returning proper values again (besides `ItunSMPB` tag)

Same here. Neurotoxin back to requiring +50 ms universal offset.

> @McKay42 out of curiosity, which version of bass are you targeting for your own projects?

- The regular Windows build of McOsu is still using the old 2.4.3.12 2009 dlls (until this is resolved),
- the exclusive mode WASAPI build is using 2.4.15.0 2019 (since december, previously 2.4.12.1 2016),
- Linux build is using 2.4.13.2 2017,
- macOS build is using 2.4.12.0 2016,
- and for non-public projects I'm always using the latest version available (2.4.15.0 2019 atm).

The exclusive mode WASAPI build has (always) had the same problems with timing, due to requiring newer dlls (since the 2009 ones did not support it yet), and also uses a hardcoded universal offset (-25 ms).

On Linux + macOS the timing is completely different anyway, but close enough to not warrant a fixed offset. They also have the same inconsistent smaller offset variations as described in #312, so I'm pretty sure this is at least deterministic.

**Comment by McKay42** [comment]
Tested with 2.4.9.0 2012 dll, perfect timing like 2009 dll. I'll see if I can find more versions.

**Comment by McKay42** [comment]
This is pretty much nailed down now:

**Comment by McKay42** [comment]
This is pretty much nailed down now:

2.4.11 - 22/12/2014
-------------------
* Support for iTunes gapless info with Media Foundation and CoreAudio codecs
	BASS_StreamCreateFile/User

This change causes both #312 and #326 here.
Switching the dlls between 2.4.11.0 and 2.4.11.14 confirms that (I couldn't find any intermediary versions).

> Agree. ItunSMPB, for instance, was not mentioned in the changelog anywhere. Will convey this.

**Comment by peppy** [comment]
The recent fixes from our end were trying to undo this offset, but it turns out that gets pretty annoying to do (while the iTunes header is readable using `BASS_TAG_GetFromFile` the xing/lame header is also required, as the iTunes gapless is only used when `ENC_DELAY` is zero).

Thankfully the bass dev was kind enough to add a flag to ignore `iTunesSMPB`. Will be pushing a release momentarily which removes the header parsing I added and uses this new flag (in my testing it works correctly across all reported maps).

**Comment by Peter-GHub** [comment]
Both maps seem to be fixed now for me 👍

**Comment by McKay42** [comment]
> Both maps seem to be fixed now for me +1

Confirmed.

Unfortunately, the smaller variations in #312 are still happening even with `BASS_CONFIG_MP3_NOITUNESTAG` and 2.4.15.1 2020 dll, for both `BASS_DEVICE_DSOUND` and WASAPI mode.

**Comment by peppy** [comment]
Good stuff, closing this issue. Will leave the other open, maybe we can figure it out.
