### ISSUE TITLE
Cursor problems

### ISSUE THREAD

**Issue by Shannanigens** [ppy/osu-stable-issues#39]
My cursor keeps randomly stopping/slowing down and jumping, tested with both mouse and tablet, tried multiple fixes and nothing has worked, only happening in osu

**Comment by BruceGamez** [comment]
That more or less sounds like a driver issue. have you tried reinstalling your driver's, or getting the latest version. Not only that, but have you tried hawku drivers? They are one of the best drivers to use for osu, and they support MANY tablets.

**Comment by MillhioreF** [comment]
This is a problem with your computer and not with the client, so it's out of scope of this repository.

**Comment by Shannanigens** [comment]
I only play with mouse, only played with tablet for a bit to see if it was the mouse causing the problem but it was happening with tablet aswell, this problem only happens in osu like I said before, in no other games or programs does my cursor randomly stop or randomly jump so I'm fairly sure it's not a computer issue

**Comment by smoogipoo** [comment]
Have you tried:

1. A different USB port.
2. Turning off/on raw input.
3. A different computer with your devices.
4. A different mouse.
5. Setting a non-unlimited frame limiter in osu!.

As mentioned this is not an issue with the client. There is something on your computer causing this, otherwise every other player would have the same issue.
