### ISSUE TITLE
The storyboard Overlay layer fails to display in Cinema mode

### ISSUE THREAD

**Issue by T0chi** [ppy/osu-stable-issues#427]
**Describe the bug:** the storyboard overlay layer isn't shown while playing a map with the cinema mod but is shown in the editor or while playing without the cinema mod. The other storyboard layers appears without any trouble, but the overlay layer is completely gone.

**osu! version:** Stable 20200320

**Comment by peppy** [comment]
Overlay is intended to be used for gameplay elements. Please link a storyboard where this applies so we can assess what the correct path is.

**Comment by T0chi** [comment]
My recently qualified storyboard makes use of the overlay layer: https://osu.ppy.sh/beatmapsets/941875#osu/2394027

Look for the spider web, vignette, cross line patterns, and flashes.

**Comment by ponoyoshi** [comment]
If needed, here is another storyboard using this layer https://osu.ppy.sh/beatmapsets/1069423#osu/2266581

**Comment by Coppertine** [comment]
https://osu.ppy.sh/beatmapsets/1067743#osu/2235465 (Vignette and particles used)
https://osu.ppy.sh/beatmapsets/1009824#fruits/2113970 (First ranked map to use Overlay (Used for both Vingette and Colour Overlay)
https://osu.ppy.sh/beatmapsets/999260#osu/2089944 (Beatmap Spotlight Winter map (would be used in timeshift soon), is only used after the first slow slider)
https://osu.ppy.sh/beatmapsets/1124097#osu/2348896 (Used as vignette and some snow particles)
https://osu.ppy.sh/beatmapsets/1008925#osu/2112130 (Used over the top of selected hitobjects)
These are just the maps I remember that are Ranked currently.

**Comment by peppy** [comment]
So how do you propose we differentiate from when the overlay should be shown instead of hidden? For instance, you probably wouldn't want to see the custom mania playfield in cinema mode, right?

I guess "overlay" should have been named "gameplay" since that *was* its original purpose..

**Comment by Coppertine** [comment]
In that case, it should be that all layers are shown, no what the layer is, as Cinema mod doesn't completely remove hitobjects, only fades them out to about 0.1 alpha (what it looks like). It should appear the same as in gameplay, but without hitobjects. in the case of the mania playfield, I think it should still be there since the original intention was to remove the original mania playfield and create a custom one.

**Comment by peppy** [comment]
The purpose of cinema mode is to show the storyboard without gameplay. Gameplay components, including storyboard overlay components that don't make sense without gameplay visible are intentionally hidden. I don't know how to make this more clear.

Hit objects are 0.1% visible because that was the only way to make hitsounds and gameplay work correctly on stable. On lazer this will not be the case.

**Comment by Coppertine** [comment]
Well, even though what was intended with cinema mode is to be as a gameplay addition, storyboarders decided to use it as a decorative addition (The Prelude To Bereavement for example, where it's the entirety of the entire storyboard).
Maybe it could allow an option within lazer (or stable) for the cinema mod to not display sprites that use the "Difficulty Spesific" option, even though that could ruin some storyboards which have that as an intended thing to either fix some issue or fit with the beatmap's background.

**Comment by T0chi** [comment]
Funny thing is I was about to ask if the Overlay layer could be named Gameplay instead so it's more clear... but might be too late now.

**Comment by Coppertine** [comment]
I think Overlay would be better as the sprites are overlaying the hitobjects, like, it sounds better than Gameplay, plus, there are ranked maps now that use `Overlay` as part of their storyboard. so it's no use..

**Comment by peppy** [comment]
I don't have an amicable solution to this. We should consider renaming the layer in lazer. I think cinema mod is working as intended here.
