### ISSUE TITLE
Auto doesn't SS some sliders when the replay is restarted.

### ISSUE THREAD

**Issue by richp2k** [ppy/osu-stable-issues#514]
This seems to happen on both stable and cutting edge
Stable:
![ezgif-7-87214a48d359](https://user-images.githubusercontent.com/66353518/90079907-398f6680-dcd7-11ea-8a37-883c57ad0b76.gif)
Cutting Edge:
![ezgif-7-075a6f1f1162](https://user-images.githubusercontent.com/66353518/90080007-82471f80-dcd7-11ea-9376-506c71baca8f.gif)

**Comment by Magnus-Cosmos** [comment]
For some reason, auto is unable to complete some sliders (usually sliders with straight ends): https://streamable.com/2qfatt
You can see that in the results screen, it has no hits, meaning the object itself never completed. This is probably due to the last frame of the replay data. [In auto's replay (on the left)](https://i.imgur.com/PM7ZnOl.png), its last frame is on 10791ms. When I add a frame right before the end time (on the right), auto is able to complete the slider.

Also, auto does not increment combo at the slidertick. Since auto doesn't have any frames during straight segments of the slider, it skips over the sliderticks.

I assume this only happens when watching a replay/restarting the replay because auto's replay data has already been generated, so the game just plays it back like a regular replay(?)

**Comment by peppy** [comment]
Should be resolved in the next release!
