### ISSUE TITLE
Taiko big hitbursts behave strangely depending on framerate

### ISSUE THREAD

**Issue by MandL27** [ppy/osu-stable-issues#551]
Semi-related to [#9860 on lazer](https://github.com/ppy/osu/issues/9860), specifically [bdach's comment](https://github.com/ppy/osu/issues/9860#issuecomment-676699839) on timing required for big hitbursts. With frame limiter set to vsync, I can fairly consistently get big hitbursts to show up when hitting both sides at the same time on big notes. With frame limiter at unlimited or optimal, I instead hear two hitsounds and see two circles fly into the HP bar, but only get the small hitburst. Result screen confirms that these were counted as small hits. Playing with the half time mod can show this behavior even on vsync, but I can also get the "intended" behavior of hit300k/100k depending on timing.

**Comment by peppy** [comment]
I'm not sure this will be fixed on stable as it's visual only, and does not affect judgements / gameplay.

**Comment by MandL27** [comment]
Ah. I thought only big hitbursts gave the point bonus, and double hitsound counted as a single small hit score-wise.

**Comment by Hiviexd** [comment]
hi, i did further testing and i figured out that this bug is not purely visual, it directly affects score judgements, specifically `countgeki` and `countkatu`, which are supposed to be the amount of finishers being hit

video below showcases 3 replays:
1. finisher isn't hit
   - result: no bonus score, 0 geki
2. finisher is hit (frame limiter is optimal, 960fps)
   - result: bonus score, 0 geki
3. finisher is hit (frame limiter is power saving, 288fps)
   - result: bonus score, 1 geki

https://www.youtube.com/watch?v=1gPd60d9yls

replay 2 is the most common use case for players. if you look at the moment the score increments, you'll notice that main score count jumps to 600, but the red score text is 300, it's safe to assume that's directly correlated with `countgeki`, and as i (and many other players) have concluded, the more framerate you have, the less of a chance the geki/katu count goes up, even if the score bonus is awarded.

you can download the map i tested on, alongside each replay here:
- map: https://nats.are-la.me/5duMUcr.osz
- replay 1: https://nats.are-la.me/8FPp9TZ.osr
- replay 2: https://nats.are-la.me/63BzLA2.osr
- replay 3: https://nats.are-la.me/46zbMj1.osr

i think fixing this would go a long way into making score stats more accurate, and would open a lot of opportunities for taiko-related medals, because we're kinda struggling with that internally as you may have noticed
