### ISSUE TITLE
osu! displays wrong accuracy in ranking panel on taiko

### ISSUE THREAD

**Issue by xxxzelda101xxx** [ppy/osu-stable-issues#552]
This was my first and second time playing this particular map

![sYmYxpYs](https://user-images.githubusercontent.com/8886218/94047350-9894d080-fd97-11ea-88d3-86a4d56ea23f.jpg)
![KStIICSF](https://user-images.githubusercontent.com/8886218/94047355-9c285780-fd97-11ea-8e3e-fdc6ec2e47a9.png)

**Comment by peppy** [comment]
What's the issue? The increase of 0.98%?

**Comment by space-server** [comment]
Yes, the the expected result should be 100.00% (+0.74%)

It seems like its using the standard accuracy formula instead of the taiko formula.

(((1 * 0.5) + (67 * 1)) * 300 / ((67 + 1 + 0) * 300) * 100) = ~99.26%
(((67 * 300) + (1 * 100) + (0 * 50) + (0 * 0)) / ((67 + 1 + 0 + 0) * 300) * 100) = ~99.02%

**Comment by xxxzelda101xxx** [comment]
Yes, the the expected result should be 100.00% (+0.74%)

It seems like its using the standard accuracy formula instead of the taiko formula.

(((1 * 0.5) + (67 * 1)) * 300 / ((67 + 1 + 0) * 300) * 100) = ~99.26%
(((67 * 300) + (1 * 100) + (0 * 50) + (0 * 0)) / ((67 + 1 + 0 + 0) * 300) * 100) = ~99.02%

**Comment by Magnus-Cosmos** [comment]
I believe this is the same issue as #519, so it's probably just broken for any non-standard mode, since it tries to compare the previous score using standard accuracy calculation.

**Comment by peppy** [comment]
This should now be resolved.
