### ISSUE TITLE
Removal of Scorev2 on high amount of beats

### ISSUE THREAD

**Issue by K3VRAL** [ppy/osu-stable-issues#632]
Some loved maps on osu!catch (https://osu.ppy.sh/beatmapsets/345834#fruits/765569 as a famous example) that go beyond the 32 bit enables scoreV2 which makes it impossible to submit plays on it. Will there be a possible fix to this issue such as instead using 64 bit instead or something else that will fix this annoyance?

It seems to be that the reason for forcing scorev2 onto maps is for a short term solution to prevent the issue from happening but it makes maps unplayable to submit scores and that gets annoying. It also raises the question of whether or not maps will have a rule not to go above the 32 bit in order to be ranked/loved.

**Comment by peppy** [comment]
The storage is not going to change. That said, this issue is already resolved in lazer (the next major release) and the solution may lie in the new scoring algorithm used there. I don't have any updates on this situation just yet, sorry. It's still on my todo list as something we need to figure out.

**Comment by K3VRAL** [comment]
Could it still be possible if some specific ranked/loved maps can evade this rule of Scorev2 being automatically added or will it cause problems in the long run, or is something that you want to be able to fix later as you don't have the time now?

My apologies if I have disturbed you
