### ISSUE TITLE
Crashing + Force Restart when changing fullscreen option

### ISSUE THREAD

**Issue by Crumpetfiddler** [ppy/osu-stable-issues#646]
Rather odd bug, by changing the full-screen option the game crashes and force restarts (despite closing the change does get saved)
the same happens for forcing fullscreen with alt+enter 

https://www.dropbox.com/s/h30q6u85o7xhv4b/2021-01-22%2022-15-13.flv?dl=0

**Comment by smoogipoo** [comment]
Please try again on the latest Cutting Edge.

**Comment by Crumpetfiddler** [comment]
Same issue is still consisting.
https://www.dropbox.com/s/5yiio3p0p16z4x6/2021-01-27%2015-39-31.flv?dl=0
Im so confused as to how this is happening

**Comment by peppy** [comment]
This is a weird one because your game is definitely being forced into compatibility mode (that's what causes the restart to occur) but there's no visual notice that it's running in compatibility mode, I guess due to the automatic fallback.

If possible please attach runtime.log after turning fullscreen off and on (preferably one for each, since it gets reset per startup).

**Comment by Crumpetfiddler** [comment]
My apologies I was at work, here is the information you requested Attached are 3 logs, 1st for just opening the game as it is, in borderless, 2nd for changing from borderless to fullscreen and the 3rd for fullscreen back to borderless, which SHOULD be the same as the first one 
[3. Changing From Fullscreen Back to Borderless - should be the same as the first log -.log](https://github.com/ppy/osu-stable-issues/files/5880458/3.Changing.From.Fullscreen.Back.to.Borderless.-.should.be.the.same.as.the.first.log.-.log)
[1. Currently Borderless.log](https://github.com/ppy/osu-stable-issues/files/5880459/1.Currently.Borderless.log)
[2. Changing From Borderless To Fullscreen.log](https://github.com/ppy/osu-stable-issues/files/5880461/2.Changing.From.Borderless.To.Fullscreen.log)

**Comment by smoogipoo** [comment]
Please provide a dxdiag log: https://support.microsoft.com/en-us/windows/open-and-run-dxdiag-exe-dad7792c-2ad5-f6cd-5a37-bf92228dfd85

What's happening here is that osu! is determining that it will fail to enter fullscreen, so it's moving to compatibility mode where it can't fail. Since this process changes the renderer, it requires a restart.. When changing back to borderless/windowed, it doesn't need compatibility mode anymore so it's changing the renderer again.

You could fix this by enabling compatibility mode while in borderless, which will keep you in compatibility mode 100% of the time, but I wouldn't exactly recommend that.

Further determination into why it's happening requires the dxdiag log.

**Comment by Crumpetfiddler** [comment]
Sure! here's the Diag.

[DxDiag.txt](https://github.com/ppy/osu-stable-issues/files/5891500/DxDiag.txt)

**Comment by smoogipoo** [comment]
Thanks. It looks like it's osu! wanting to enter compatibility mode too aggressively here. I'll look into it.

**Comment by smoogipoo** [comment]
This will be fixed in the next Cutting Edge build :)

**Comment by Crumpetfiddler** [comment]
Great to hear! 
I'll leave another comment / edit this current comment should my issue be resolved when the update hits. Thanks so much for your help!

**Comment by peppy** [comment]
The update has already been pushed to all release streams.

**Comment by Crumpetfiddler** [comment]
I see. That was fast. I'll check straight away when I finish work
