### ISSUE TITLE
Closing the editor crashes the game

### ISSUE THREAD

**Issue by Matiyasu** [ppy/osu-stable-issues#674]
When I close the beatmap editor, the image crashes, but the music still plays (as seen in the video)

https://user-images.githubusercontent.com/76702041/109778225-dc241e00-7c04-11eb-9d89-acf158083f88.mp4

logs:
[runtime.log](https://github.com/ppy/osu-stable-issues/files/6074616/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/6074617/session.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/6074618/update_success.log)

**Comment by peppy** [comment]
Have you tried running windowed? Does it resolve the issue?

Also have you tried... turning off that obscenity that is running on your desktop?

**Comment by Matiyasu** [comment]
Okay, turning off the full screen seems to work, and the live wallpaper wasn’t the problem

**Comment by Matiyasu** [comment]
But I also want to ask if it’s a common issue

**Comment by peppy** [comment]
There are some issues surrounding switching display modes, and it's often hard to discern whether the problem is at our end, or due to changes in video card drivers. If this is something that only started recently, it's likely due to a driver change, but also a hard one for us to investigate and fix.

I would recommend using windowed mode for now. We hope to improve this kind of issue in lazer (the next major update).
