### ISSUE TITLE
Performance/lag issues with cutting-edge compatibility mode

### ISSUE THREAD

**Issue by zeusminus** [ppy/osu-stable-issues#719]
During the gameplay, when the beatmap exits from break time, the gameplay ms goes over 20-30 and stays as is until the user quits the beatmap. For the record, I haven't tested the other modes, just encountered it while playing osu!catch.

![](https://cdn.discordapp.com/attachments/728234128495083530/830510623275089960/screenshot327.jpg)

After further tests w/ Dnt, we deduced that the issue might be connected to the new ANGLE fix, due to the following:
- started only recently (possibly related to the March 27 update)
- only happens with Compatibility Mode
- only happens on the Cutting-Edge version (latest)

Additionally, the chat window also happens to be quite laggy during CE Compatibility Mode. I'm not sure if it's related but there exists a possibility as both of these issues were resolved when I switched to the Stable version.

**Comment by smoogipoo** [comment]
It's definitely related to the ANGLE changes since I've seen other reports of this, but unsure why.

1. Can you post all files from the logs folder in your osu! directory?
2. Are you running in fullscreen (not borderless)? And if so, can you confirm you're getting exclusive fullscreen - are you seeing tearing with vsync off?
3. Please post a dxdiag report (https://support.microsoft.com/en-us/windows/open-and-run-dxdiag-exe-dad7792c-2ad5-f6cd-5a37-bf92228dfd85).

**Comment by zeusminus** [comment]
1. [performance.log](https://zeu.s-ul.eu/2EkE0VpG.log), [update_success.log](https://zeu.s-ul.eu/Esshr4yp.log), [network.log](https://zeu.s-ul.eu/mF3TRVVx.log), [runtime.log](https://zeu.s-ul.eu/6AIdJUog.log), [update.log](https://zeu.s-ul.eu/i1VgHTjv.log), [session.log](https://zeu.s-ul.eu/eLycP9Jx.log)
2. Yes, it's running in fullscreen. I believe I'm encountering screen tearing occasionally as well, so I suppose I can confirm.
3. [DxDiag Report](https://zeu.s-ul.eu/jUOSAzmb.txt)

**Comment by smoogipoo** [comment]
Closing as the change has been reverted for the time being.
