### ISSUE TITLE
Change 4.0x SV limitation in the F6 timing panel to 10.0x, which is the game's maximum

### ISSUE THREAD

**Issue by iptq** [ppy/osu-stable-issues#731]
Right here:

![image](https://user-images.githubusercontent.com/1700346/115131547-88a43e80-9fbe-11eb-9cb8-340578973719.png)

Right now this has to be changed through the .osu file. The game supports slider multipliers up to 10.0x, so I don't see why this is necessarily still capped at 4.

**Comment by peppy** [comment]
This settings was set to be roughly in line with ranking criteria expectations. Are we seeing beatmaps with higher than 4x ranked on a regular basis these days?

**Comment by Nivalyx** [comment]
hmm, from what i see they are becoming somewhat more common nowadays yeah (the top diff my recently ranked [FEVER DREAM](http://osu.ppy.sh/beatmapsets/1405913#osu/2899195) mapset has a super short 1/8 slider that goes on 5.5x SV for example) but at the same time i don't think that these stuffs are being "ranked on a regular basis" or anything like that either 😦

the thing with extreme SV values is — although they're not unrankable or anything — you have to *really* know what you're doing (and be *really* justified in your design choice) in order for them to work properly. if this change got through i can see more or less two things happening :

a) it'll help (certain) experienced mappers to create (certain) slider arrangements on (some certain) songs and circumstances, but

b) at the same time it'll also encourage newer mappers to use extreme SV values in their mapping just for the sake of it ("i want it there for the hype" "i want it there to make the map difficult and challenging" "i want it there so that all the top players are more interested in looking into my map in their twitch streams" etc.) which is not a right a right step to take imo. 

---

if any i'm... indifferent with this proposed change i guess :x

**Comment by Purplegaze** [comment]
honestly I think if any super new mapper is setting ridiculously high sv on their maps, they're probably not actually trying to improve their mapping and learn -- it would be for a meme anyway (or at least, the things that new mappers would learn from getting feedback on such a map would be exactly the same with or without 10x sliders), so it's not like allowing them to use it is really changing anything for the worse. anyone further than being a complete noob at mapping probably would know better.

and on the other hand, plenty of advanced mappers currently have to resort to editing .osu files any time they want to make maps focused on fast sliders -- these types of maps often change SV very very frequently, which makes creating such maps really frustrating when SVs have to be changed past 4 multiple times in a row

imo this would be overall a positive thing to change

**Comment by iptq** [comment]
(sorry my mail broke for a few days so I didn't get any notifications about updates to this thread)

I ranked a [map back in 2019](https://osu.ppy.sh/beatmapsets/754103#osu/1595588) with a 6x slider and even maps like [this](https://osu.ppy.sh/beatmapsets/554892#osu/1174596) from back in 2017 were using 5x sliders in their maps. I don't know of other examples off the top of my head but it seems to be very common given how fast slider maps go these days. Sure, the use case of it is rare but I also think requiring editing the .osu file for something there's already a UI for is kind of annoying

wrt second point: I think editor limitations shouldn't be a way to "teach" newer mappers; if anything, they can already create garbage within the current 4.0x limit and it's not like limiting to 1.5x would help at all. I also don't really like the idea of "guiding" mappers down a specific path either, since the editor should just be an empty canvas for creation without thinking specifically of pushing maps to ranked and conforming to criteria.

**Comment by peppy** [comment]
As we've pretty much already done this in lazer, I don't see a reason not to allow in stable too. Added in next cutting edge release.
