### ISSUE TITLE
Make DT & HT change on-screen AR/OD/HP values

### ISSUE THREAD

**Issue by Edythator** [ppy/osu-stable-issues#740]
For as long as the map difficulty values have been shown on-screen, they haven't ever been displayed correctly with DT/HT. Instead, you've got an arrow signifying that the values have either gone up or down in difficulty. 
![dt](https://edythator.xyz/c/KCUnvS0g.png)
![ht](https://edythator.xyz/c/g5CneDoN.png)

This is as opposed to HR/EZ, which actually shows you the exact values with the mods enabled and even a red/blue tint to signify a difficulty change.
![hr](https://edythator.xyz/c/jO3LKUtA.png)
![ez](https://edythator.xyz/c/g0q8nrvQ.png)

This has created mass confusion over the years, up to the point where osu! players have had to manually learn what values DT/HT gives off on a certain AR/OD/HP. This becomes especially problematic when you encounter maps with a decimal place in its difficulty properties. Changing this would be significantly more user-friendly and save time not having to do manual labor.

**Comment by peppy** [comment]
This is probably best discussed on the lazer repository, as it fundamentally changes what that display means. I don't foresee this being changed in stable. @smoogipoo confirm and close if agree.

**Comment by smoogipoo** [comment]
This is because DT indirectly changes these values by changing the audio rate. Definitely not going to happen in stable - too complex to calculate HP especially.

It's actually quite difficult to calculate in both stable and lazer due to the different meanings per-ruleset - What does AR mean? What does OD mean? Both of these are not as simple as multiplying/dividing by 1.5.

In lazer, we're unsure yet whether OD is going to keep the same mechanic or whether OD will remain the same at all times (https://github.com/ppy/osu/issues/12248, consideration for long long down the line). But feel free to make another issue covering this in there - I have quite a few suggestions for paths to take.
