### ISSUE TITLE
taiko-bar-left.png clipped early

### ISSUE THREAD

**Issue by mon** [ppy/osu-stable-issues#741]
I have a taiko skin I've been using since 2013 which had a little cover around the hit target after a note becomes late:
![firefox_27ikitwFKf](https://user-images.githubusercontent.com/3398021/116070695-47074800-a6d0-11eb-9fb6-3a062684cb0f.png)

Sometime in early 2020 it stopped working and is now clipped:
![i_view32_9C8gZXqoXQ](https://user-images.githubusercontent.com/3398021/116070776-5ab2ae80-a6d0-11eb-97fa-496a271c0ef1.png)

The skin's taiko-bar-left in particular:
![taiko-bar-left](https://user-images.githubusercontent.com/3398021/116071019-a9604880-a6d0-11eb-9cd9-67f430977131.png)

Looking at #393 it seems like it might have been patched at the same time and for a similar reason.

Is this particular behaviour a bug or is the clipping intentional to stop exploits?

**Comment by peppy** [comment]
This is intentional. You can change the way your skin works to avoid this, but it will require modifying the sprites.

**Comment by noderoo** [comment]
This is disappointing. If this is meant to prevent people from abusing taiko-bar-left as a lane cover, consider that they can just stick a piece of paper over their screen and get away with it anyway. I'm curious how else I'm supposed to wrap a semi-circle around the judgement area. taiko-slider moves, so it's unsuitable, and taiko-bar-right is useless for anything but vertical gradients because it gets stretched by weird amounts on widescreen resolutions.
