### ISSUE TITLE
osu! Doesn't Display Some Non-Latin Scripts Despite the Existence of Unicode Blocks Containing Them

### ISSUE THREAD

**Issue by esmb17** [ppy/osu-stable-issues#760]
The specific script I have found the client does not display is Tifinagh script. I don't really see it being very hard to implement support for the display of characters from a significantly wider array of languages as are supported by Unicode.

https://en.wikipedia.org/wiki/Tifinagh_(Unicode_block)

**Comment by esmb17** [comment]
Oh and no it does not work in lazer either. It just displays "?????".

**Comment by smoogipoo** [comment]
Yes, there are quite a lot of scripts that osu!stable doesn't support. This has not been requested any time before and it's a waste of time to add support to every script.

Lazer's a whole different issue entirely, because it doesn't even have support for using system fonts right now (ever?), and those unicode ranges aren't supported by any fonts we have.
