### ISSUE TITLE
mania's 6key mode and 8key mode mod:random doesn't make some random

### ISSUE THREAD

**Issue by kz9p2nr52z** [ppy/osu-stable-issues#762]
Applying Mod: Random with mania's 6 keys mode and 8 keys mode doesn't randomize the first lane,
It will be fixed no matter how many times you retry.
May I ask for confirmation?
The red part of XD(Pages 5 and 7) seems to be a bug.
https://xd.adobe.com/view/47fb094d-e33c-4684-909d-f37a227e7d8c-12a8/

osu! version: Stable 20210520.2 (latest)
https://osu.ppy.sh/community/forums/topics/1329607

**Comment by smoogipoo** [comment]
Mania will not randomise what it thinks is the special column. It should probably be doing this based on the beatmap's configuration, but it's hard to say whether this is not the case for some historical reasons.

I'm going to call this out of scope, because:
- Fixing it requires a new replay version and I'm not sure that's easy to add in this case.
- Fixed in lazer, but lazer doesn't consider the beatmap's configuration at all.
- The mod isn't used all that often (I think?).
- It's unranked.

**Comment by kz9p2nr52z** [comment]
Thank you for your confirmation.
I understand why it's difficult to fix.
I want to continue playing, so I would appreciate it if you could correct it if possible.
