### ISSUE TITLE
osu score upload bug

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-stable-issues#786]
[session.log](https://github.com/ppy/osu-stable-issues/files/6709813/session.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/6709814/update.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/6709815/update_success.log)
[network.log](https://github.com/ppy/osu-stable-issues/files/6709816/network.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/6709817/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/6709818/runtime.log)

I probably know how to quickly trigger this bug. First, change the ranking to global ranking, and quickly switch the map. When there is no ranking on the left side when playing, this bug will appear.
It is also possible to trigger this bug when changing the map at normal speed.

Rate upload is ok.

video
https://user-images.githubusercontent.com/26690346/123277856-0e9db200-d539-11eb-8085-5d5704fcc956.mp4

**Comment by peppy** [comment]
Please check your runtime log. This is likely occurring because you have some very long paths in your beatmaps folder, and therefore it can't complete online retrieval ahead of time.

Please move your osu! folder to a less-nested location on disk or find the paths which are too long and delete them.
