### ISSUE TITLE
full-OS 15+s freeze while playing (cutting edge)

### ISSUE THREAD

**Issue by Zyfarok** [ppy/osu-stable-issues#788]
Since about a week ago (maybe last monday ?), me and a friend that is also using cutting edge started experiencing very regular (multiple times per hour) full-OS freezes from 2-3 to 15+ seconds while playing after osu! has been open for "a while" (30+ min).

I've never experienced this before and it started happening last week for both of us, which means It could be due to a recent Windows 10 update(s) though but I guess it's good to have the issue open here to investigate ?

osu! version : cutting edge (20210606)
Both of our Windows 10 build : 19042.1052
Our Nvidia driver version : 471.11 and 466.11

**Comment by peppy** [comment]
Need performance log files if you want our help to diagnose your PC's issues.

Turn on performance logging and provide all log files after the freeze occurs.

**Comment by Zyfarok** [comment]
I completely forgot about the existence of those logs. I had a new windows update last night (now running 19042.1081) and did not encounter such freezes again in 2+ hours (I'll send the log if anything happens again), but my friend didn't do this windows update yet and had a similar freeze again today !

Here are his performance logs (the freeze happens at 15:24 UTC, he stopped the game right after the freeze to save and send me the logs) :
https://mega.nz/folder/UkxyQCLC#upM_z24YBNkFixpUgIz8qQ

The permance.log file is also available here :
https://gist.github.com/Zyfarok/b015e740abdceb2ac40cec0d7c61d7e8

**Comment by peppy** [comment]
Can you confirm that the pauses where while at song select?

If so, the log is showing the something is hanging up the windows event loop, on input or otherwise. This is the most common cause of performance issues. Basically means something else on your system is blocking the whole operating system (including osu!) from doing anything.

Can't really help further than this. A good starting point may be to find the apps which both you and your friend have in common then look for those which could potentially have an effect on performance (overlays, hotkey managers etc.)

**Comment by Zyfarok** [comment]
> Can you confirm that the pauses where while at song select?

Yes it's the 8.7s frametime at `15:25:21`. Thanks for the info. I have very very few non-microsoft background processes and services on my PC and another friend has encountered similar problems on another game recently, so it's highly probably windows related.

Thanks for the help.
