### ISSUE TITLE
Objects disappeared after using "snap objects to new timing" in editor.

### ISSUE THREAD

**Issue by Clawtch** [ppy/osu-stable-issues#791]
Applying "snap objects to new timing" when using a snap divider of 1/9 or smaller would cause all objects disappear. This issue happens in every beatmap, and reinstalling the game doesn't solve the issue.

**Comment by frukoyurdakul** [comment]
I'm attaching a video sample about what's going on about the bug.

[Here is the video regarding to the issue](https://user-images.githubusercontent.com/33460209/127036123-da7b8ff1-8d40-4531-afc3-7040d8608837.mp4)

The solution is pretty simple actually, found by somebody named "duski" in game. This is what they wrote:

"the thing is, the settings are just "misaligned", like the snapping shown in the panel has probably indexes for each snapping and then they added the new snaps but didnt change the indexing. So now if you use something like 1/7 on the panel, it actually snaps to 1/16 or something and then if you use a higher one than 1/7 or whatever the limit istheres no snapping left in the editorso it nukes the map."

This is completely right, I've tested myself. The previous values were

- 1/1
- 1/2
- 1/3
- 1/4
- 1/6
- 1/12
- 1/24

Now the values are (and the behaviors):

- 1/1
    - works correctly
- 1/2
    - works correctly
- 1/3
    - works correctly
- 1/4
    - works correctly
- 1/5
    - works correctly (with 1/5 snap divisor) 
- 1/6
    - works correctly
- 1/7 (actual value: 1/12) --> here is where I think the index starts to shift
    - **works incorrectly** (uses 1/12 snap, not 1/7 snap)
- 1/8 (actual value: 1/24) 
    - **works incorrectly** (uses 1/24 snap, not 1/8 snap)
- 1/9 (actual value: none)
    - **removes the notes**
- 1/12 (actual value: none)
    - **removes the notes**
- 1/24 (actual value: none)
    - **removes the notes**

Implementing the actual snapping functionality would be a plus, but I think "removing all notes" is a pretty crucial bug, which should be fixed in my opinion.

Thank you for your time.

**Comment by peppy** [comment]
Thanks for the report. A fix for this is in the pipeline and should hit in the next cutting edge release.
