### ISSUE TITLE
Boss key is broken under wine due to being disabled manually

### ISSUE THREAD

**Issue by jvyden** [ppy/osu-stable-issues#794]
Hello,

I noticed a feature named called "boss key" when playing osu! on Windows yesterday. When I tried to use it on Linux today, it didn't work.

I investigated and found [this thread](https://osu.ppy.sh/community/forums/topics/362773) explaining it had been disabled due to a bug that happened 6 years ago. 

Because of it's age, I decided to see if this was still the case. I decided to build Wine and remove the `wine_get_version` function from `ntdll` and sure enough it started working. I also noticed other features like cursor pinning, the normal osu! font's numbers, and the transparency during exit started working.

Seeing as all of this works just fine, could it be re-enabled?

**Comment by peppy** [comment]
Not really willing to potentially break compatibility with existing wine installs. If your workaround works for you then I'd just stick with it.

@thepoon thoughts on this one?

**Comment by ThePooN** [comment]
Thanks for reporting your success.

There are moderate chances that this will affect some people. On Linux, although major desktop environments should have no such issue with this level of integration nowadays, I'm not so sure about more niche and minimalist DEs (although I'm not very experienced with them to be honest), and with Wayland added to the mix, the Linux desktop is very segmented atm. And there's also macOS, which is generally less supported, so that adds even more unknowns.
I fear this is asking for trouble and not worth it, especially as lazer is very mature nowadays and should be preferred when using Linux or macOS.

However, if this works fine for you, then you can continue using work-arounds. In fact, I may have a simpler one for you: if you use `wine-staging`, you can unexpose Wine's methods (such as `wine_get_version` from `ntdll`) in the "Staging" tab of `winecfg`.

Please let us know if that works; if it doesn't, I think we may adjust our Wine detection method to make sure it does.

**Comment by Beyley** [comment]
I can confirm that hiding the wine ver from the Staging tab does get around the detection, and i can confirm that all features that are blocked do work great for me (im running wine 6.12 on Xorg XFCe with the kernel version `Linux 5.12.14-arch1-1`)

I dont have a mac to test with but i can prob message a friend that does have one to see if they can help me test, and message some other friends with really customized (and outdated) wine installs to see if it would actually break or not, ill edit this post when i get more info, because if it doesnt seem to break anything and works on mac too, then it might actually be worth reenabling the blocked options, with a way to redisable them if things go awry on specific installs (maybe an option in settings or a flag in the .cfg files in worst case idk)

**Comment by peppy** [comment]
It's not going to happen. stable is feature locked and I am not interested in potentially breaking things.
