### ISSUE TITLE
cropped hp bars on the latest update

### ISSUE THREAD

**Issue by shiguonosu** [ppy/osu-stable-issues#822]
title is self explanatory, idk if this happens only for animated hp bars but this is still an issue, and it isnt a skin problem
![scorebar-colour-0@2x](https://user-images.githubusercontent.com/53843204/130159586-f197dbf1-11ce-4aed-afa4-4bd7c6a2c846.png)
^ original file
![Capture](https://user-images.githubusercontent.com/53843204/130159618-40b2afaf-7dcf-4488-873f-fdf5949d5d07.PNG)
^ what the latest update does to it

**Comment by shiguonosu** [comment]
heres the skin link for anybody that wants it (i did some personal edits on the sc, the one im using is the og one)
https://cdn.discordapp.com/attachments/822327204423008287/822333226798415913/-_-_Codename__kdoge_2.0_A.K.A_kdoges_Shirakami_Fubuki_v4.1.0_KSE_Revamped.osk

**Comment by h3oCharles** [comment]
retired skinner here, what do you exactly mean by "cropped" here?

**Comment by shiguonosu** [comment]
bottom of the health bar color is cropped, as i showed in the picture

**Comment by Magnus-Cosmos** [comment]
This is an intended change, see #800

**Comment by shiguonosu** [comment]
ah, i see peppy's intuition is to cuck skinners as well, epic

**Comment by peppy** [comment]
Please try to understand that this change was not to "cuck" skinners. It was to fix a reported exploit and keep the game safe.

From the beginning, we have attempted to provide template skin elements with dimensions but users have gone beyond these without there being an official specification. It's hard to deal with. We are not trying to fuck you over.

You can still fix this by editing your skin to use the background layer of the score at for tall elements (rather than the fill layer)

Thanks for understanding.
