### ISSUE TITLE
logo on startup screen doesnt appear transparent 

### ISSUE THREAD

**Issue by GStudiosX2** [ppy/osu-stable-issues#837]
![image](https://user-images.githubusercontent.com/76548041/132556556-ca8295fa-083a-4378-bb1e-23bc57bdfc19.png)

intel i5-7200u
intel hd graphics 620
windows 10 20h2

**Comment by peppy** [comment]
not sure, must be something on your system. check any settings you changes recently

**Comment by GStudiosX2** [comment]
> not sure, must be something on your system. check any settings you changes recently

i haven't changed any settings this is the only game where this happens so i dont know what could be wrong

**Comment by Rekunan** [comment]
This also happens to me, but I just assumed that it's caused by my low specs (Intel i5-5300U; Intel(R) HD Graphics 5500; Windows 10 Pro 21H1) If anyone needs repro steps, open up osu!, wait for the osu! cookie to show up and then change whatever is below the osu! cookie (here I just scrolled up my discord) 
![image](https://user-images.githubusercontent.com/24501632/132607595-d8c88eb0-5c87-4dde-a035-070f9c556ae7.png)

**Comment by GStudiosX2** [comment]
> This also happens to me, but I just assumed that it's caused by my low specs (Intel i5-5300U; Intel(R) HD Graphics 5500; Windows 10 Pro 21H1) If anyone needs repro steps, open up osu!, wait for the osu! cookie to show up and then change whatever is below the osu! cookie (here I just scrolled up my discord)
> ![image](https://user-images.githubusercontent.com/24501632/132607595-d8c88eb0-5c87-4dde-a035-070f9c556ae7.png)

could it be something to do with the intel graphics ?
or could it be a error in the game?

**Comment by GStudiosX2** [comment]
ah someone said that the logo isnt transparent and it just takes whatever is on your screen currently this should be fixed?

**Comment by peppy** [comment]
That is intended behaviour.

**Comment by GStudiosX2** [comment]
> That is intended behaviour.

hmm yeah but it kinda looks weird like cant you do something about it?

**Comment by smoogipoo** [comment]
No, it's out of scope of this repo.
