### ISSUE TITLE
There is a system-cursor and osu-cursor on the game screen when mouse is re-plugged

### ISSUE THREAD

**Issue by labo-China** [ppy/osu-stable-issues#851]
As title, this problem occurs definitely. The cursor in game is still works, but Windows cursor does not work in game.
And because of the different DPI between system and game, two cursors will move by different speed.
I have been changed my mouse device, but the problem always occurs.

This problem can only be fixed by restarting game now.
![image](https://user-images.githubusercontent.com/62234752/134756288-76049879-808d-4434-b1a4-a86fa6d81262.png)

Platform: Windows 10 19042.1237
Mouse: A4Tech OP-520NU
OSU: 20210920
Raw-input: enabled
Display mode: Fullscreen (1600x900)

**Comment by peppy** [comment]
This is going to either be your mouse driver software, or some other app on your system unhiding the mouse. Cannot reproduce.

**Comment by labo-China** [comment]
> This is going to either be your mouse driver software, or some other app on your system unhiding the mouse. Cannot reproduce.

How about unplug and plug-in the mouse again? My previous title may be misleading, please check it again. (my English sucks, sorry)

**Comment by peppy** [comment]
Yes I did try exactly that, with two different mice. But I also know from the API we are using that this cannot happen from re-plugging a device. Something else on your system is calling a system-wide "show cursor" call. You can resolve it by alt-tabbing away and back into osu! if this is something you don't wish to find the root cause of.
