### ISSUE TITLE
two cursors appearing instead of one (Redirected from ppy/osu)

### ISSUE THREAD

**Issue by raybeanosu** [ppy/osu-stable-issues#941]
logs here: 
[message (2).txt](https://github.com/ppy/osu-stable-issues/files/8041611/message.2.txt)

**i have already referred to #851 before sending this post, no it doesn't fix this issue.**

posting this for a friend who uses a tablet, and is seeing two cursors instead of one. this is what she said,

> so i use my stylus and suddenly i get two spammy cursors, so when i move it around it either clicks stuff or obviously doesnt get the circles

the double cursors go away when switching from tablet to mouse, but returns back again on switching back, unplugging mouse doesn't make a difference either.

a reddit help thread suggested reinstalling osu, but that did not work as well.

screenshots: 
![20220210_160520](https://user-images.githubusercontent.com/91675300/153424815-45ccc924-c44e-4fee-8798-db016303cfae.jpg)

![20220210_160531](https://user-images.githubusercontent.com/91675300/153424828-646d1f9a-f5ac-492e-bf82-0dc63663c0fc.jpg)

**Comment by peppy** [comment]
Turn off raw input.

**Comment by raybeanosu** [comment]
> 

it was already off. apparently this is a pc issue?

**Comment by smoogipoo** [comment]
Are one of the cursors fixed in place until you move the mouse?  If so, this sounds like you have some program on your system constantly sending mouse inputs, which is coincidentally also what tablets do, as opposed to only sending inputs when the position actually changes.

Perhaps it's some sort of mouse driver such as Razer Synapse though I wouldn't expect them to do _anything_ when the mouse is unplugged, or perhaps it's an external utility you installed.

There's nothing we can do here in any case.
