### ISSUE TITLE
AiMod doesn't show some unsnapped objects.

### ISSUE THREAD

**Issue by SMOKELIND** [ppy/osu-stable-issues#957]
Noticed on this [osz](https://smokelind.s-ul.eu/9HHcIUXG) that AiMod doesn't show any errors regarding snaps.
![iKQD2nw](https://user-images.githubusercontent.com/64348887/158202332-d0b70022-2f42-4b29-9a59-5952fc82175f.png)
Meanwhile those are actually unsnapped and also mentioned in Mapset Verifier.
![TCXPMWT](https://user-images.githubusercontent.com/64348887/158202512-51b9a0c2-000a-494c-a46d-da894a665ba4.png)
Assuming caused after change here https://github.com/ppy/osu-wiki/pull/6873

**Comment by peppy** [comment]
Unsnapped by 2ms is considered acceptable. Do you have any examples of higher values?

**Comment by SMOKELIND** [comment]
Thought anything more than 2ms ( even 2.1ms ) is supposed to be marked as it used to be. Higher values more than 3ms are appearing fine.

**Comment by Naxesss** [comment]
From my observations objects other than the first selected *may* shift 1 ms every time a copy paste happens on a different part of the timeline (due to snapping being cast to int). 1 ms unsnaps are therefore quite common, while 2 ms are rare. 3+ ms should be even rarer, but not impossible if a group of objects are copy pasted 3 times or more.

Up until this point we set the threshold at exactly 2 ms (and is what has been in use for the past 6+ years), but if you want to change that rule to use 3 ms instead, then I could update MV and lazer accordingly. Would be good to know of in the future for transparency, though - as far as I knew only the false positive was fixed.

**Comment by peppy** [comment]
Okay so let's take a step back.

https://github.com/ppy/osu-wiki/pull/6873#issuecomment-1035955602 says that we want to *not* show snaps which are 1ms, so I increased the leniency to 2ms. This issue is saying that we *do* want to show 2ms snaps.

The way stable works, without making some larger changes, I need to set a lenience of either 1ms or 2ms. The sliders in this thread are reporting 2ms and therefore being hidden with the new setting. If I change it back to 1ms, the previous reports will return.

I guess the issue here is that the external app you're viewing is working in floating point space while stable isn't?

**Comment by Naxesss** [comment]
> I guess the issue here is that the external app you're viewing is working in floating point space while stable isn't?

This is it. The discrepancy can be shown like this (here 333.33 ms per beat with offset 0):
| Space | Slider Start | Slider End | Closest End Snap | End Unsnap | |
|:-|:-|:-|:-|:-|:-|
| Floating Point | 332 | 665.33 | 667 | -1.66 | <-- lazer, MV |
| Integer | 332 | 665 (cast to int) | 667 | -2 | <-- AiMod |

I understand changing this behaviour in stable is probably not cost-effective on your end, which is why we wanted to push https://github.com/ppy/osu-wiki/pull/6873 to handle these edge cases gracefully. We then seem to have miscommunicated what the actual issue was, leading to where we are now.

The reports were rare and none were false negatives, so given what you said, I think reverting to 1 ms and merging https://github.com/ppy/osu-wiki/pull/6873 is best. The other option is making other tools work in integer space, but that seems a bit backwards.

**Comment by peppy** [comment]
I'm taking one last attempt at this, which is live on cutting edge. Please re-test all edge cases if possible.

**Comment by SMOKELIND** [comment]
Did some testing, now it looks like all unsnapped objects are showing properly with any value >=2, so it seems to be fine atm.

On other hand ( Not fully sure if it happened after this change or was already before ), AiMod now points out some slider ends as using rare divisor incorrectly ( i.e. 1/2, 1/4 slider ends show 1/12 snap warning and similar ).  Can't really know what's the cause of this, but it happens on almost any map.
Judging from timestamps in AiMod they are unsnapped by 1ms, but Mapset Verifier doesn't mention any, so assuming it's related to current change.

**Comment by SMOKELIND** [comment]
Actually not all showing properly, seeing maps that were mentioned here https://github.com/ppy/osu-wiki/pull/6873. They have same kind of unsnaps as they used to have before all the changes.
The intended change here would be having no warnings regarding unsnaps on mentioned maps, and also while checking AiMod and Mapset Verifier their unsnap mentions would be the same.

**Comment by peppy** [comment]
@Naxesss confirm one thing for me because i'm a bit lost here as to how to make this work. no matter what i try one of the provided test cases is off.

the "Comfort" difficulty in this thread, focusing specifically on the first issue slider (ending at `79757`):

![Parallels Desktop 2022-03-17 at 05 36 55](https://user-images.githubusercontent.com/191335/158744042-92f0a0e9-b563-4dd5-a540-ff45a2b00042.png)

The snap difference here according to stable (with floating-point checks) is 1.44ms, but your app is reporting as 2.019 in the OP screenshot. Do you know where this discrepancy comes from?

**Comment by Naxesss** [comment]
Formula:
```
unsnap = endTime - snapTime
endTime = startTime + sliderDuration
sliderDuration = sliderPxLength / sliderSpeed
sliderSpeed = 100 * startLineSVMult * globalSVMult / startLineMsPerBeat
```

Calculation (formula in reverse):
```
sliderSpeed = 100 * 1.0 * 2.0 / 468.01872074883 = 0.4273333333
sliderDuration = 200 / sliderSpeed = 468.01872074883
endTime = 797289 + sliderDuration = 79757.01872074883
unsnap = endTime - 79755 = 2.01872074883
```

Hence `unsnap = 2.019`.

One cause of the discrepancy is that my `snapTime`  and your `snapped` is not the same. Although I do not show it above, I first calculate the decimal value like you do, but then I cast it to an integer to account for all snaps being cast to integer in the game. This way if an object is "snapped" to the timeline, it will have an unsnap of 0, which I think is most intuitive.

The other cause is that my `endTime` and your `time` is different. It seems like `time` lost accuracy somehow, perhaps by being converted to an integer somewhere before reaching this method?

Once those two are fixed, this specific case will work the same as lazer/MV.

For full parity, however, also replace `<= 2.01` with `< 2.0`, and consider all possible snappings; 1/5, 1/7, 1/9, 1/12, and 1/16. Can see how I did the latter in [lazer](https://github.com/ppy/osu/blob/21348e6620069ba6cbc749201756849c95b0a802/osu.Game/Beatmaps/ControlPoints/ControlPointInfo.cs#L160)/[MV](https://github.com/Naxesss/MapsetParser/blob/8f14354073ed9f2c4723bbd96ac8602cdc6693b6/objects/Beatmap.cs#L729) for reference. If you would like, I'd be happy to help with the code.

**Comment by riffysu** [comment]
> I'm taking one last attempt at this, which is live on cutting edge. Please re-test all edge cases if possible.

there's an interesting thing that i'm seeing now. aimod reports wrong (rare) snap divisors on practically every map. 

just as an example, checking https://osu.ppy.sh/beatmapsets/973171#osu/2046861 basically any diff of this set gives you a ton of false notifications on rare snaps. as far as i can tell, every single slider gets reported as using rare snap divisor 

![image](https://user-images.githubusercontent.com/74588145/159181611-2c374c13-dd79-4f74-b75e-72c398dd9416.png)

happens on the latest cutting edge build, does not appear on beta.

**Comment by peppy** [comment]
Already aware of this, but thanks for pointing it out again.

**Comment by peppy** [comment]
I'm going to rollback all changes and call this fixed. Please adjust the ranking criteria as you see fit.
